#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Deploy script for Email Signature Generator on AWS Free Tier.
.DESCRIPTION
    1. Builds and deploys SAM stack
    2. Gets output values (API URL, Frontend bucket)
    3. Generates frontend config with API URL
    4. Syncs frontend files to S3
#>

param(
    [string]$StackName = "email-signature-generator",
    [string]$Region = "us-east-1",
    [switch]$SkipBackend,
    [switch]$FrontendOnly
)

$ErrorActionPreference = "Stop"

Write-Host "`n=== Email Signature Generator - AWS Deployment ===" -ForegroundColor Cyan

# Step 1: Build and deploy backend (SAM)
if (-not $SkipBackend -and -not $FrontendOnly) {
    Write-Host "`n[1/4] Building SAM application..." -ForegroundColor Yellow
    sam build --template-file template_aws.yml
    if ($LASTEXITCODE -ne 0) { throw "SAM build failed" }

    Write-Host "`n[2/4] Deploying SAM stack..." -ForegroundColor Yellow
    sam deploy --template-file template_aws.yml --stack-name $StackName --region $Region --resolve-s3 --capabilities CAPABILITY_IAM --no-confirm-changeset
    if ($LASTEXITCODE -ne 0) { throw "SAM deploy failed" }
}

# Step 2: Get stack outputs
Write-Host "`n[3/4] Retrieving stack outputs..." -ForegroundColor Yellow
$outputs = aws cloudformation describe-stacks --stack-name $StackName --region $Region --query "Stacks[0].Outputs" --output json | ConvertFrom-Json

$apiUrl = ($outputs | Where-Object { $_.OutputKey -eq "ApiUrl" }).OutputValue
$frontendUrl = ($outputs | Where-Object { $_.OutputKey -eq "FrontendUrl" }).OutputValue
$frontendBucketName = $frontendUrl -replace "http://", "" -replace "\.s3-website.*", ""

Write-Host "  API URL: $apiUrl" -ForegroundColor Green
Write-Host "  Frontend URL: $frontendUrl" -ForegroundColor Green
Write-Host "  Frontend Bucket: $frontendBucketName" -ForegroundColor Green

# Step 3: Generate frontend config with API URL
Write-Host "`n[4/4] Deploying frontend to S3..." -ForegroundColor Yellow

# Create a config.js that sets the API base URL
$configContent = @"
// Auto-generated by deploy script - DO NOT EDIT manually
window.API_BASE_URL = '$apiUrl';
"@

$configPath = Join-Path $PSScriptRoot "..\frontend\config.js"
Set-Content -Path $configPath -Value $configContent -Encoding UTF8

# Sync frontend files to S3
aws s3 sync ./frontend "s3://$frontendBucketName" --delete --region $Region
if ($LASTEXITCODE -ne 0) { throw "Frontend S3 sync failed" }

# Clean up generated config (don't want it in git)
Remove-Item $configPath -ErrorAction SilentlyContinue

Write-Host "`n=== Deployment Complete! ===" -ForegroundColor Green
Write-Host "`nYour application is live at:" -ForegroundColor Cyan
Write-Host "  Frontend: $frontendUrl" -ForegroundColor White
Write-Host "  API:      $apiUrl" -ForegroundColor White
Write-Host "`nNote: It may take a minute for CloudFormation to finish propagating." -ForegroundColor DarkGray
